### ISSUE TITLE
feat: Googleログインを実装

### ISSUE THREAD

**Issue by yussak** [yussak/goal-app#50]
- [x] ログイン可能にする
- [x] 登録可能にする
- [ ] credentials削除
- [ ] userId使用可能にする（できなくなったため）
- [ ] goalなどのCRUD可能な状態に戻す

**Comment by YusukeSakuraba** [comment]
まずemailがない時

**Comment by YusukeSakuraba** [comment]
ハマった
公式もissueもウェブ記事も役に立つものが見つけられず・・・

**Comment by yussak** [comment]
nextauthはGoogleログインなどに力を入れてるようなのでそれに絞ろうと思った
無理してmail, passwordにするメリットないので

**Comment by yussak** [comment]
普通にログインしただけだとDBのusersテーブルに追加されない

**Comment by yussak** [comment]
思ったより手間がかかる上にメリットないとわかったのでクローズ
