### ISSUE TITLE
目標機能の設計

### ISSUE THREAD

**Issue by yussak** [yussak/goal-app#70]
目標詳細ページ（思いついてから書ける）に中目標を用意するかのラジオボタンを用意

```
中目標を用意する？
◉YES
○NO
```

選択肢後から変えられるべき？→YES。でも実装手間かかりそうなので一旦は変えられないで進める

中目標がないなら「中目標を入力してください」フォームを出す

```
中目標を用意する？
◉NO

[TODOを入力してください]
[追加]
```

YESの場合

```
中目標を用意する？
◉YES

[中目標を入力してください]
[追加]
```

小、TODOはどうするか

**Comment by YusukeSakuraba** [comment]
時間の関係で一旦目標、中目標、TODO固定で実装する
